### ISSUE TITLE
Booster Installation - Wrong binary!

### ISSUE THREAD

**Issue by sduensin** [pydio/pydio-doc-admin-guide#2]
After weeks of arguing with my Pydio installation I discovered that the documentation for installing Booster directs you to download a binary that is four releases out of date!

I suggest a symlink from "current" to the current release directory so all URLs pointing to the download area can avoid being updated every time a new release ships.

Or better yet, put the binary in the DEBs.

**Comment by cdujeu** [comment]
Scott, can you point to the exact documentation page?  thx

**Comment by sduensin** [comment]
Sure.  This page has the only download link I could find on the site:

https://pydio.com/en/docs/v8/install-pydio-booster-manually

**Comment by bsinou** [comment]
Closing issues that have been fixed.
