### ISSUE TITLE
LDAP/AD Group Setup - Wrong URL

### ISSUE THREAD

**Issue by sduensin** [pydio/pydio-doc-admin-guide#3]
On https://pydio.com/en/docs/v8/binding-ldapad-server the link to "Groups and Roles with LDAP/AD integration" leads to https://pyd.io/groups-and-roles-with-ldapad-integration-draft/ and is covered with a really annoying dialog I can't close.

**Comment by bsinou** [comment]
Closing issues that have been fixed long time ago.
