### ISSUE TITLE
TLS Offloading not supported by Cells

### ISSUE THREAD

**Issue by ciphermenial** [pydio/pydio-doc-admin-guide#8]
There should be a warning that Cells does not work with TLS Offloading. I spent far too long trying to figure out what I was doing wrong only to discover the way Caddy configures ports and accepted connections means you can not do TLS Offloading.

[This page](https://pydio.com/en/docs/cells/v2/run-cells-behind-proxy) should have the warning note about this.

**Comment by bsinou** [comment]
If I understand your point correctly and we have the same notion of TLS Offloading, that is not completely true:

We have many instance where we have:
WWW === HTTPS ===> REVERSE PROXY === HTTP ===> CELLS

Yet, this is an issue if you want to use the Sync client that relies on gRPC over HTTP/2

Anyway, I have updated [this page](https://github.com/pydio/pydio-doc-admin-guide/blob/cells-v2/2_running_cells_in_production/3_run_behind_a_proxy.md) on our doc (not yet published): let me know if you do not agree or if you have further question.
 
Thanks for the feedback.
